# Generated by Django 3.0.3 on 2020-06-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='breathing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='dry_cough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='flu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='other_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=36.5, max_digits=3),
        ),
    ]
