# Generated by Django 3.0.3 on 2020-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0003_auto_20200707_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
