# Generated by Django 3.0.3 on 2020-06-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0005_auto_20200623_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='breathing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='dry_cough',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='flu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='other_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(default=False),
        ),
    ]
