# Generated by Django 3.0.3 on 2020-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0008_auto_20200623_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='dry_cough',
            field=models.BooleanField(default=False),
        ),
    ]
