# Generated by Django 3.0.3 on 2020-06-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_locations',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
