# Generated by Django 3.0.3 on 2020-06-15 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=264)),
                ('city', models.CharField(choices=[('Swakopmund', 'Swakopmund'), ('Walvis Bay', 'Walvis Bay'), ('Windhoek', 'Windhoek'), ('Other', 'Other')], default='Walvis Bay', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
